### PR TITLE
fix(Image): throw an error if an alt tag is not passed

### PR DESCRIPTION
**Pull request by nathunsmitty**
I actually caught an alt tag not being passed in our tests while implementing this lol

### CODE REVIEW

**Comment by nathunsmitty** [comment]
This would also be a good PR for an intern to review! @caziz @aybeshlikyan @rajivanisetti @seichang00 @sarahc7

**Comment by zeehang** [comment]
Assuming we're using this for main site that means we'll need to have writers/editors write alt tags for each photo that's on the site?

**Comment by nathunsmitty** [comment]
@zeehang yup!

**Comment by nathunsmitty** [comment]
I got it thank you for the catch @ryang72!

**Comment by ryang72** [comment]
Realized that this would break existing sites using lux images that don't have alt tags, so I think we should either make this a major release to prevent auto updating or update all the previous lux images that don't have an alt tag before merging?

**Comment by nathunsmitty** [comment]
Yes on the major release. Which Lux projects continuously use the latest version?

**Pull request merged**
